### PR TITLE
MOD-6343 Fix potential crash for cf.reserve (#724)

### PR DESCRIPTION
**Pull request by YaacovHazan**

### CODE REVIEW

**Review by tezc — DISMISSED** [review]

**Review by tezc — APPROVED** [review]

**Comment by filipecosta90** [comment]
### Automated performance analysis summary

This comment was automatically generated given there is performance data available.

In summary:
- Detected a total of 14 stable tests between versions.
- Detected a total of 3 improvements above the improvement water line.
- Detected a total of 2 regressions bellow the regression water line 5.0.

You can check a comparison in detail via the [grafana link](https://benchmarksrediscom.grafana.net/d//q4-5sRR7k/?var-branch=master&var-branch=feature-temp-check-2.4-1)

### Comparison between master and feature-temp-check-2.4-1.

Time Period from 30 days ago. (environment used: oss-standalone)

|                     Test Case                      |Baseline master (median obs. +- std.dev)|Comparison feature-temp-check-2.4-1 (median obs. +- std.dev)|% change (higher-better)|           Note            |
|----------------------------------------------------|----------------------------------------|-----------------------------------------------------------:|------------------------|---------------------------|
|bf_add_cap10M_err0.001                              | 144919 +- 6.0% (7 datapoints)          |                                                      143879|-0.7%                   |waterline=6.0%. No Change  |
|cf_add_cap10M                                       | 158095 +- 5.5% (7 datapoints)          |                                                      158725|0.4%                    |waterline=5.5%. No Change  |
|cms_add_err0.001_prob0.01                           | 160635 +- 4.7% (7 datapoints)          |                                                      155032|-3.5%                   |potential REGRESSION       |
|tdigest_add_comp100                                 | 150369 +- 3.7% (7 datapoints)          |                                                      161935|7.7%                    |IMPROVEMENT                |
|tdigest_add_comp1000                                | 144919 +- 7.4% (7 datapoints)          |                                                      140837|-2.8%                   |waterline=7.4%. No Change  |
|tdigest_add_comp200                                 | 147050 +- 3.5% (7 datapoints)          |                                                      139854|-4.9%                   |potential REGRESSION       |
|tdigest_add_comp50                                  | 148142 +- 4.8% (7 datapoints)          |                                                      161938|9.3%                    |IMPROVEMENT                |
|tdigest_add_comp500                                 | 157470 +- 2.9% (7 datapoints)          |                                                      124217|-21.1%                  |REGRESSION                 |
|tdigest_merge_2hist_1M_samples_comp100              | 69614 +- 5.7% (7 datapoints)           |                                                       75580|8.6%                    |waterline=5.7%. IMPROVEMENT|
|tdigest_quantile_p50_1M_samples_comp100             | 132659 +- 3.1% (7 datapoints)          |                                                      135226|1.9%                    |No Change                  |
|tdigest_quantile_p50_1M_samples_comp1000            | 130720 +- 4.0% (7 datapoints)          |                                                      131115|0.3%                    |No Change                  |
|tdigest_quantile_p50_1M_samples_comp200             | 133579 +- 3.0% (7 datapoints)          |                                                      131985|-1.2%                   |No Change                  |
|tdigest_quantile_p50_1M_samples_comp50              | 132421 +- 4.1% (7 datapoints)          |                                                      132207|-0.2%                   |No Change                  |
|tdigest_quantile_p50_1M_samples_comp500             | 133225 +- 2.9% (7 datapoints)          |                                                      132898|-0.2%                   |No Change                  |
|tdigest_quantile_p50_p95_p99_p999_1M_samples_comp100| 123460 +- 1.9% (7 datapoints)          |                                                      126264|2.3%                    |No Change                  |
|tdigest_quantile_p95_1M_samples_comp100             | 134317 +- 4.1% (7 datapoints)          |                                                      139509|3.9%                    |potential IMPROVEMENT      |
|tdigest_quantile_p99_1M_samples_comp100             | 131815 +- 2.6% (7 datapoints)          |                                                      135358|2.7%                    |No Change                  |
|tdigest_trimmed_mean_1M_samples_comp100             | 132734 +- 2.5% (7 datapoints)          |                                                      136135|2.6%                    |No Change                  |
|topk_incrby_k100                                    | 142341 +- 4.7% (7 datapoints)          |                                                      134223|-5.7%                   |REGRESSION                 |

**Comment by haishredis** [comment]
MOD-6343

**Comment by ashtul** [comment]
@YaacovHazan  I would recommend to change the default of MAX_ITERATIONS to 255. Going beyond is not likely to achieve anything. I would also change MAX_EXPANTION to 16 or even less since the ERROR_RATE accumulate and at 16 you are at 50% so flipping a coin would make much more sense.

**Comment by LiorKogan** [comment]
@ashtul we were on the safe side here. We don't want to break any user. Surely not on a patch version.

**Comment by YaacovHazan** [comment]
Done by https://github.com/RedisBloom/RedisBloom/pull/728

**Comment by YaacovHazan** [comment]
Thanks @ashtul. We will review it and take it into a different PR.

**Comment by LiorKogan** [comment]
@ashtul regarding "flipping a coin would make much more sense": correct me if I'm wrong, but this is not exactly so - this is about the **false positive** error rate, so yes, the false positive error rate would reach 50%, but this is unlike coin tossing where the error rate would reach 50%.

**Pull request closed without merging**
