### PR TITLE
Coverage badge using DoceCov

### PR DESCRIPTION
**Pull request by ashtul**

### CODE REVIEW

**Comment by ashtul** [comment]
Message on the current missing badge is "No commits found on master yet." 
So I expected once we merge it, it will show the stats.

**Comment by gkorland** [comment]
@ashtul thanks! looks good, I guess we just need to add more tests now...

**Comment by ashtul** [comment]
@gkorland some are checks we don't want to spend the time emulating.
Kudos to @rafie for helping out.

**Comment by gkorland** [comment]
@ashtul  we need to cover error paths too.
but if there are paths you think are not related to the module we should mark them for ignore

**Pull request merged**
