### PR TITLE
fix pow calculate

### PR DESCRIPTION
**Pull request by lintanghui**

### CODE REVIEW

**Comment by lintanghui** [comment]
any update? @ashtul

**Comment by ashtul** [comment]
@lintanghui 
I think the change has to be in line 82:
`topk->lookupTable[i] = pow(decay, i - 1);`
then in line 144:
`decay = topk->lookupTable[*countPtr - 1];`
and in 147:
`decay = pow(topk->lookupTable[TOPK_DECAY_LOOKUP_TABLE],`

WDYT?

**Comment by lintanghui** [comment]
> 

if in line 82,  `topk->lookupTable[i] = pow(decay, i - 1)`
then topk->lookptable[0] will to be pow(x,-1), it may have ambiguity
when *countPtr =1 , it will get a decay (topk->lookuptable[0] ) greater than 1 (decay^-1)

**Comment by ashtul** [comment]
@lintanghui You are correct.
It should be `topk->lookupTable[i] = pow(decay, i + 1)`. `[1-256]` instead of `[0-255]`.

**Comment by lintanghui** [comment]
@ashtul i think the current change is better, or maybe the look up table  should be init with cap `TOPK_DECAY_LOOKUP_TABLE + 1`

**Comment by lintanghui** [comment]
@ashtul i think the current change is better, or maybe the look up table  should be init with cap `TOPK_DECAY_LOOKUP_TABLE + 1`

**Review by ashtul — APPROVED** [review]

**Comment by ashtul** [comment]
@lintanghui can you please sign the CLA?

**Comment by lintanghui** [comment]
i had sign the cla but something seem to be err

**Pull request merged**
